// <auto-generated />
using System;
using HabitTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407170442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HabitTracker.Domain.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Habits", (string)null);
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.HabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "DateLogged");

                    b.ToTable("HabitEntries", (string)null);
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.HabitEntry", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.CodingSession", "CodingSession", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("int");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("int");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.CommunicationDetail", "CommunicationDetail", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("int");

                            b1.Property<int>("ConfidenceScore")
                                .HasColumnType("int");

                            b1.Property<string>("Reflection")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("SkillFocusedOn")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.GymSession", "GymSession", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("int");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal>("WeightKg")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("WorkoutType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.NutritionDetail", "NutritionDetail", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("int");

                            b1.Property<int>("Calories")
                                .HasColumnType("int");

                            b1.Property<int>("CarbohydratesGrams")
                                .HasColumnType("int");

                            b1.Property<int>("FatGrams")
                                .HasColumnType("int");

                            b1.Property<decimal>("ProteinGrams")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.Navigation("CodingSession");

                    b.Navigation("CommunicationDetail");

                    b.Navigation("GymSession");

                    b.Navigation("NutritionDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
